blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_home, name='blog'),
    path('<int:pid>', blog_single, name = 'single'),
    path('category/<str:cat_name>', blog_category, name = 'category'),
    path('author/<str:author_username>', blog_home, name='author'),
    path('search/', blog_search, name='search'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('zarinpal/', include('zarinpal.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', store_views, name='home'),
    path('category/<str:cat_name>',category_views, name='category'),
    path('<int:pid>',product_views, name='product'),
    path('comment',product_comment, name='comment'),
    path('add_to_cart',add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<str:cart_item_id>',remove_from_cart, name='remove_from_cart'),
    path('remove_from_cart2/<str:cart_item_id>',remove_from_cart2, name='remove_from_cart2'),
    path('cart_detail',cart_detail, name='cart_detail'),
    path('cart_refresh',cart_refresh, name='cart_refresh'),
    path('cart_detail_2',cart_detail2, name='cart_detail2'),
    path('cart_detail_3',cart_detail3, name='cart_detail3'),
    path('cart_detail_4',cart_detail4, name='cart_detail4'),
]

templates/folder/archive.html
<!--  ==========  -->
<!--  = Archive =  -->
<!--  ==========  -->

<div class="sidebar-item widget_archive">
    <div class="underlined">
        <h3><span class="light"> آرشیو </span>نوشته های بلاگ</h3>
    </div>
    {% for name, count in categories.items %}
    <ul>
        <li><a title={{name}} href="{% url 'blog:category' cat_name=name %}">{{ name }}</a>&nbsp;({{ count }})</li>
    </ul>
    {% endfor %}
</div>

templates/folder/cart.html
{% load humanize %}
<div class="span3">
    <div class="cart-container" id="cartContainer">
        <div class="cart">
            <p class="items">سبد خرید <span class="dark-clr">{{total_product}}</span></p>
            <p class="dark-clr hidden-tablet">مجموع : {{total_price|intcomma}}</p>
            <a href="{% url 'store:cart_detail' %}" class="btn btn-danger">
                <!-- <span class="icon icons-cart"></span> -->
                <i class="icon-shopping-cart"></i>
            </a>
        </div>
        <div class="open-panel">
            {% for i in cart_items %}
            <div class="item-in-cart clearfix">
                <div class="image">
                    <img src="{{ i.product.image.url }}"
                        width="124" height="124" alt="cart item" />
                </div>
                <div class="desc">
                    <strong><a href="product.html">{{ i.product.name }}</a></strong>
                    <span class="light-clr qty">
                        تعداد : {{ i.quantity }}
                        &nbsp;
                        <a href="{% url 'store:remove_from_cart2' cart_item_id=i.id %}" title="Remove Item">❌</a>
                    </span>
                </div>
                <div class="price">
                    <strong>{{ i.product.price|intcomma }}</strong>
                </div>
            </div>
            {% endfor %}
            <div class="summary">
                <div class="line">
                    <div class="row-fluid">
                        <div class="span6">هزینه ارسال :</div>
                        <div class="span6 align-right">$4.99</div>
                    </div>
                </div>
                <div class="line">
                    <div class="row-fluid">
                        <div class="span6">جمع کل :</div>
                        <div class="span6 align-right size-16">{{total_price|intcomma}}</div>
                    </div>
                </div>
            </div>
            <div class="proceed">
                <a href="{% url 'store:cart_detail' %}"
                    class="btn btn-danger pull-right bold higher">تسویه حساب <i
                        class="icon-shopping-cart"></i></a>
                <small>هزینه ارسال بر اساس منطقه جغرافیایی محاسبه میشود. <a href="#">اطلاعات
                        بیشتر</a></small>
            </div>
        </div>
    </div>
</div> <!-- /cart -->