blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_home, name='blog'),
    path('<int:pid>', blog_single, name = 'single'),
    path('category/<str:cat_name>', blog_category, name = 'category'),
    path('author/<str:author_username>', blog_home, name='author'),
    path('search/', blog_search, name='search'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('zarinpal/', include('zarinpal.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', store_views, name='home'),
    path('category/<str:cat_name>',category_views, name='category'),
    path('<int:pid>',product_views, name='product'),
    path('comment',product_comment, name='comment'),
    path('add_to_cart',add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<str:cart_item_id>',remove_from_cart, name='remove_from_cart'),
    path('remove_from_cart2/<str:cart_item_id>',remove_from_cart2, name='remove_from_cart2'),
    path('cart_detail',cart_detail, name='cart_detail'),
    path('cart_refresh',cart_refresh, name='cart_refresh'),
    path('cart_detail_2',cart_detail2, name='cart_detail2'),
    path('cart_detail_3',cart_detail3, name='cart_detail3'),
    path('cart_detail_4',cart_detail4, name='cart_detail4'),
]

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index, name='home'),
    path('contact', contact, name='contact'),
    path('niknews',SendEmail, name='niknews'),
    path('search', website_search, name='search'),
    path('about_us',about_us, name='about_us'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from jdatetime import date

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Post(models.Model) :
    image = models.ImageField(upload_to='blog', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.title, self.id)
    
    def shamsi_publish_date(self):
           return date.fromgregorian(date=self.published_at)
    
    class Meta:
        ordering = ('-created_at',)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.first_name+' '+self.last_name

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm) :
    class Meta:
        model = Comment
        fields = ['post','user','first_name','last_name','message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment
from django.utils import timezone
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from django.contrib import messages
from blog.forms import CommentForm

# Create your views here.
def blog_home(request, **kwargs) :
    now = timezone.now()
    posts = Post.objects.filter(status=1).exclude(published_at__gt=now).order_by('-published_at')
    if kwargs.get('author_username'):
        posts = posts.filter(author__username=kwargs['author_username'])
    posts = Paginator(posts, 4)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger :
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(request, 'blog.html', context)

def blog_single(request,pid) :
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS, 'کامنت شما در صف بررسی قرار گرفت')
        else:
            messages.add_message(request,messages.ERROR, 'کامنت شما ثبت نشد')

    post = get_object_or_404(Post, pk=pid, status=True)
    comments = Comment.objects.filter(post=post.id, approved=True)
    cc = comments.count()
    post.counted_views += 1
    post.save()
    context = {'post': post, 'comments': comments, 'cc': cc}
    return render(request, 'blog-single.html', context)

def blog_category(request, cat_name):
    now = timezone.now()
    posts = Post.objects.filter(status=True, category__name=cat_name).exclude(published_at__gt=now).order_by('-published_at')
    posts = Paginator(posts, 4)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger :
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(request, 'blog.html', context)

def blog_search(request):
    now = timezone.now()
    posts = Post.objects.filter(status=1).exclude(published_at__gt=now)
    if request.method == 'GET':
        if s:= request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {'posts': posts}
    return render(request, 'blog.html', context)

templates/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}


<!--  ==========  -->
<!--  = Breadcrumbs =  -->
<!--  ==========  -->
<div class="darker-stripe">
    <div class="container">
        <div class="row">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <a href="{% url 'website:home' %}">وبمارکت</a>
                    </li>
                    <li><span class="icon-chevron-right"></span></li>
                    <li>
                        <a href="{% url 'blog:blog' %}">بلاگ</a>
                    </li>
                    <li><span class="icon-chevron-right"></span></li>
                    <li>
                        <a href="{{ request.path }}">{{request.path}}</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="push-up top-equal blocks-spacer">
        <div class="row">

            <!--  ==========  -->
            <!--  = Main Title =  -->
            <!--  ==========  -->

            <div class="span12">
                <div class="title-area">
                    <h1 class="inline"><span class="light">بلاگ</span> وبمارکت</h1>
                    <h2 class="inline tagline">- جایی که آدمهای باهوش، حرفهای احمقانه میزنند!</h2>
                </div>
            </div>

            <!--  ==========  -->
            <!--  = Main content =  -->
            <!--  ==========  -->
            <section class="span8 single single-post">

                <!--  ==========  -->
                <!--  = Post =  -->
                <!--  ==========  -->
                <article class="post format-video">
                    <div class="post-inner">
                        <!-- <iframe src="{{ post.image.url }}" width="620" height="349" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> -->
                        <img src="{{ post.image.url }}" alt='{{ post.title }}' alt="{{post.title}}" />
                        <div class="post-title">
                            <h2><span class="light">{{post.title}}</h2>
                            <div class="metadata">
                                {{ post.shamsi_publish_date }}
                                /
                                نوشته شده توسط : <a title="View all posts in aciform"
                                    href="#">{{post.author.get_full_name}}</a>
                                /
                                تعداد بازدید : {{ post.counted_views }}
                            </div>
                        </div>
                        <p>{{post.content|safe}}</p>
                    </div>
                </article>

                <hr />

                <!--  ==========  -->
                <!--  = Comments =  -->
                <!--  ==========  -->

                <section id="comments" class="comments-container">
                    <h3 class="push-down-25"><span class="light">{{cc}}</span> نظر</h3>

                    <!--  ==========  -->
                    <!--  = Single Comment =  -->
                    <!--  ==========  -->
                    {% for i in comments %}
                    <div class="single-comment clearfix">
                        <div class="avatar-container">
                            {% if i.user.profile.image.url %}
                            <div class="avatar"
                                style="width: 100px; height: 100px; border-radius: 50%; background-image: url('{{i.user.profile.image.url}}'); background-size: cover;">
                            </div>
                            {% else %}
                            <!-- <img src="{% static 'images/default.jpg' %}" alt="avatar" class="avatar" width="184"
                                height="184" style="border-radius: 50%;" /> -->
                            <div class="avatar"
                                style="width: 100px; height: 100px; border-radius: 50%; background-image: url('{% static 'images/default.jpg' %}'); background-size: cover;">
                            </div>
                            {% endif %}
                        </div>
                        <div class="comment-content">
                            <div class="comment-inner">
                                <cite class="author-name">
                                    <span class="light">{{i.first_name}} {{i.last_name}}</span>
                                </cite>
                                <div class="metadata">
                                    <!-- 26 فروردین 1392 در 12:30 بعد از ظهر -->
                                    <span dir="ltr">{{ i.created_at|naturaltime }}</span>
                                </div>
                                <div class="comment-text">
                                    <p>{{i.message}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <hr />

                    <h3 class="push-down-25"><span class="light">نظر</span> بدهید</h3>

                    <form id="commentform" method="post" action="{% url 'blog:single' pid=post.id %}"
                        class="form form-inline form-comments">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                        <input type="hidden" name="user" value="{{request.user.id}}">
                        {% endif %}
                        <input type="hidden" name="post" value="{{post.id}}">
                        <p class="push-down-20">
                            <input type="text" aria-required="true" name="first_name" tabindex="1" size="30" value=""
                                id="author" name="author" required>
                            <label for="author">نام<span class="red-clr bold">*</span></label>
                        </p>
                        <p class="push-down-20">
                            <input type="text" aria-required="true" name="last_name" tabindex="1" size="30" value=""
                                id="author" name="author" required>
                            <label for="author">نام خانوادگی<span class="red-clr bold">*</span></label>
                        </p>
                        <p class="push-down-20">
                            <textarea class="input-block-level" name="message" tabindex="4" rows="7" cols="70"
                                id="comment" name="comment" placeholder="نظرتان را در اینجا بنویسید ..."
                                required></textarea>
                        </p>
                        <p>
                            <button class="btn btn-primary bold" type="submit" tabindex="5" id="submit">ارسال
                                نظر</button>
                        </p>
                    </form>

                </section>

            </section> <!-- /main content -->

            <!--  ==========  -->
            <!--  = Sidebar =  -->
            <!--  ==========  -->
            <aside class="span4 right-sidebar">
                <!--  ==========  -->
                <!--  = Flickr Widget =  -->
                <!--  ==========  -->
                <div class="sidebar-item widget_flickr">
                    <div class="underlined">
                        <h3><span class="light">ابزارک</span> فلیکر</h3>
                    </div>

                    <div class="flickr-badge clearfix">
                        <!-- Start of Flickr Badge -->
                        <div id="flickr_badge_uber_wrapper">
                            <div id="flickr_badge_wrapper">
                                <script type="text/javascript"
                                    src="http://www.flickr.com/badge_code_v2.gne?count=9&display=random&size=s&layout=x&source=all_tag&tag=surf&user=29003388%40N04"></script>
                            </div>
                        </div>
                        <!-- End of Flickr Badge -->
                    </div>
                </div>

                {% postcategories %}

                <!--  ==========  -->
                <!--  = Twitter Widget =  -->
                <!--  ==========  -->
                <div class="sidebar-item widget_archive">
                    <div class="underlined">
                        <h3><span class="light"> یکمی جا </span>برای متن های دلخواهمون</h3>
                    </div>
                    <p>این پروژه یک فروشگاه آنلاین بر پایه جنگو می‌باشد که به مدیر سایت امکان اضافه کردن متن‌های دلخواه
                        را فراهم می‌کند. با استفاده از این قابلیت، مدیران سایت می‌توانند مطالب، خبرها یا توضیحات محصولات
                        را به آسانی به وبسایت خود اضافه کرده و آن را به روز نگه دارند. یکی از مزایای استفاده از چارچوب
                        جنگو برای این پروژه، سرعت و کارایی بالاست. جنگو با داشتن یک ساختار کدی منظم و قوی، توسعه سریع و
                        بهینه‌ای را برای توسعه‌دهندگان فراهم می‌کند.
                    </p>
                    <p>
                    از طرفی، یکی از معایب جنگو ممکن است پیچیدگی آن برای مبتدیان باشد. چارچوب جنگو شامل بخش‌های
                    متعددی از جمله ORM (Object-Relational Mapping)، تشخیص واسط کاربری، مدیریت تصاویر و... است که
                    ممکن است برای کسانی که تازه وارد این حوزه هستند، یادگیری آنها زمان بیشتری را اشغال کند. با این
                    حال، با انعطاف‌پذیری و توانایی بالای جنگو، این معایب نیز قابل پیش‌بینی و قابل حل هستند.</p>
                </div>
            </aside> <!-- /sidebar -->
        </div>
    </div>
</div> <!-- /container -->


{% endblock %}

templates/checkout-step-1.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->

<head>
	<meta charset="utf-8">
	<title>Webmarket HTML Template - Checkout Step 1</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="ProteusThemes">

	<!--  Google Fonts  -->
	<link
		href='http://fonts.googleapis.com/css?family=Pacifico|Open+Sans:400,700,400italic,700italic&amp;subset=latin,latin-ext,greek'
		rel='stylesheet' type='text/css'>

	<!-- Twitter Bootstrap -->
	<link href="{% static 'stylesheets/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'stylesheets/responsive.css' %}" rel="stylesheet">
	<!-- Slider Revolution -->
	<link rel="stylesheet" href="{% static 'js/rs-plugin/css/settings.css' %}" type="text/css" />
	<!-- jQuery UI -->
	<link rel="stylesheet" href="{% static 'js/jquery-ui-1.10.3/css/smoothness/jquery-ui-1.10.3.custom.min.css' %}"
		type="text/css" />
	<!-- PrettyPhoto -->
	<link rel="stylesheet" href="{% static 'js/prettyphoto/css/prettyPhoto.css' %}" type="text/css" />
	<!-- main styles -->

	<link href="{% static 'stylesheets/main.css' %}" rel="stylesheet">



	<!-- Modernizr -->
	<script src="{% static 'js/modernizr.custom.56918.js' %}"></script>

	<!-- Fav and touch icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/apple-touch/144.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/apple-touch/114.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/apple-touch/72.png' %}">
	<link rel="apple-touch-icon-precomposed" href="{% static 'images/apple-touch/57.png' %}">
	<link rel="shortcut icon" href="{% static 'images/apple-touch/57.png' %}">
</head>


<body class=" checkout-page">

	<div class="master-wrapper">

		{% if messages %}
		<div id="myContent">
			<div
				style="text-align: center; padding-top: 5px; border: 10px; margin: 10px; font-size: x-large; font-family: 'Courier New', Courier, monospace;">
				<ul class="messages">
					{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
						{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
						{{ message }}
						</li>
						{% endfor %}
				</ul>
			</div>
		</div>
		{% endif %}
		<script>
			setTimeout(function () {
				document.getElementById("myContent").style.display = "none";
			}, 10000); // 5000 میلی‌ثانیه معادل 5 ثانیه است
		</script>


		<div class="container">
			<div class="row">

				<!--  ==========  -->
				<!--  = Main content =  -->
				<!--  ==========  -->
				<section class="span12">

					<div class="checkout-container">
						<div class="row">
							<div class="span10 offset1">

								<!--  ==========  -->
								<!--  = Header =  -->
								<!--  ==========  -->
								<header>
									<div class="row">
										<div class="span2">
											<a href="index.html"><img src="{% static 'images/logo-bw.png' %}"
													alt="Webmarket Logo" width="48" height="48" /></a>
										</div>
										<div class="span6">
											<div class="center-align">
												<h1><span class="light">بازبینی</span> سبد خرید</h1>
											</div>
										</div>
										<div class="span2">
											<div class="right-align">
												<img src="{% static 'images/buttons/security.jpg' %}"
													alt="Security Sign" width="92" height="65" />
											</div>
										</div>
									</div>
								</header>

								<!--  ==========  -->
								<!--  = Steps =  -->
								<!--  ==========  -->
								<div class="checkout-steps">
									<div class="clearfix">
										<div class="step active">
											<div class="step-badge">1</div>
											سبد خرید
										</div>
										<div class="step">
											<div class="step-badge">3</div>
											آدرس ارسال
										</div>
										<div class="step">
											<div class="step-badge">2</div>
											شیوه پرداخت
										</div>
										<div class="step">
											<div class="step-badge">4</div>
											تایید و پرداخت
										</div>
									</div>
								</div> <!-- /steps -->

								<!--  ==========  -->
								<!--  = Selected Items =  -->
								<!--  ==========  -->
								<table class="table table-items">
									<thead>
										<tr>
											<th colspan="2">آیتم</th>
											<th>
												<div class="align-center">تعداد</div>
											</th>
											<th>
												<div class="align-right">قیمت</div>
											</th>
										</tr>
									</thead>
									<tbody>
										<form action="{% url 'store:cart_refresh' %}" method="get">
											{% for i in cart_items %}
											<tr>
												<td class="image"><img src="{{ i.product.image.url }}" alt=""
														width="124" height="124" /></td>
												<td class="desc">{{ i.product.name }} &nbsp; <a title="Remove Item"
														class="icon-remove-sign"
														href="{% url 'store:remove_from_cart' cart_item_id=i.id %}"></a>
												</td>
												<td class="qty">
													<input type="number" min="1" style="width: min-content;"
														name="n{{i.id}}" value="{{ i.quantity }}"
														max="{{i.product.inventory}}" />
													<input type="hidden" name="p{{i.id}}" value="{{ i.id }}" />
												</td>
												<td class="price">
													{{ i.product.price }}
												</td>
											</tr>
											{% endfor %}
											<div style="text-align: center;">
												<button type="submit"
													style="background-color: white; padding: 10px; border-radius: 10px;">تازه
													سازی سبد خرید</button>
											</div>
										</form>
										<tr>
											<td colspan="2" rowspan="2">
												<div class="alert alert-info">
													<button data-dismiss="alert" class="close" type="button">×</button>
													هزینه ارسال بر اساس منطقه جغرافیایی محاسبه میشود. <a
														href="#">اطلاعات بیشتر</a>
												</div>
											</td>
											<td class="stronger">هزینه ارسال :</td>
											<td class="stronger">
												<div class="align-right">$4.99</div>
											</td>
										</tr>
										<tr>
											<td class="stronger">جمع کل :</td>
											<td class="stronger">
												<div class="size-16 align-right">{{total_price}}</div>
											</td>
										</tr>
									</tbody>
								</table>

								<hr />
								{% if total_price %}
								<p class="right-align">
									در مرحله بعدی شما آدرس ارسال را انتخاب خواهید کرد. &nbsp; &nbsp;
									<a href="{% url 'store:cart_detail2' %}"
										class="btn btn-primary higher bold">ادامه</a>
								</p>
								{% else %}
								<p class="right-align" style="font-size: larger; color: red;">
								 شما که محصولی در سبد خرید ندارید دوست عزیز !&nbsp; &nbsp;
								</p>
								{% endif %}
							</div>
						</div>
					</div>


				</section> <!-- /main content -->

			</div>
		</div> <!-- /container -->




	</div> <!-- end of master-wrapper -->



	<!--  ==========  -->
	<!--  = JavaScript =  -->
	<!--  ==========  -->

	<!--  = FB =  -->

	<div id="fb-root"></div>
	<script>(function (d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=126780447403102";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>


	<!--  = jQuery - CDN with local fallback =  -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="text/javascript">
		if (typeof jQuery == 'undefined') {
			document.write('<script src="js/jquery.min.js"><\/script>');
		}
	</script>

	<!--  = _ =  -->
	<script src="{% static 'New folder/underscore/underscore-min.js' %}" type="text/javascript"></script>

	<!--  = Bootstrap =  -->
	<script src="{% static 'New folder/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  = Slider Revolution =  -->
	<script src="{% static 'New folder/jquery.themepunch.plugins.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'New folder/jquery.themepunch.revolution.min.js' %}" type="text/javascript"></script>

	<!--  = CarouFredSel =  -->
	<script src="{% static 'New folder/jquery.carouFredSel-6.2.1-packed.js' %}" type="text/javascript"></script>

	<!--  = jQuery UI =  -->
	<script src="{% static 'New folder/jquery-ui-1.10.3.custom.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'New folder/touch-fix.min.js' %}" type="text/javascript"></script>

	<!--  = Isotope =  -->
	<script src="{% static 'New folder/jquery.isotope.min.js' %}" type="text/javascript"></script>

	<!--  = Tour =  -->
	<script src="{% static 'New folder/bootstrap-tour.min.js' %}" type="text/javascript"></script>

	<!--  = PrettyPhoto =  -->
	<script src="{% static 'New folder/jquery.prettyPhoto.js' %}" type="text/javascript"></script>

	<!--  = Google Maps API =  -->
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="js/goMap/js/jquery.gomap-1.3.2.min.js"></script>

	<!--  = Custom JS =  -->
	<script src="{% static 'New folder/custom.js' %}" type="text/javascript"></script>

</body>

</html>

templates/news.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>news</title>
    <style>
        body {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
        }

        form {
            margin-top: 20px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 10);
        }

        input[type="text"] {
            width: 100%;
            height: 10em;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <form action="{% url 'website:niknews' %}" method="post">
        {% csrf_token %}
        <input type="text" name="subject" placeholder="Enter subject here!">
        <input type="text" name="content" placeholder="Enter content here!">
        <button type="submit">Send News</button>
    </form>
</body>

</html>